# Netlify Configuration for Clippings

[build]
  # No build command needed - static site
  publish = "."

[[headers]]
  # Apply these headers to all routes
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Don't cache HTML
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Don't cache config.js (allows easy updates)
  for = "/config.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Custom 404 page (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
